### ISSUE TITLE
When I go to the page and create databases

### ISSUE THREAD

**Issue by burkaslarry** [php4dev/heroku-wordpress#1]
It goes blank page

**Comment by javadev** [comment]
I will recheck current master with a new heroku application.

**Comment by burkaslarry** [comment]
![Screenshot 2019-05-06 15 14 54](https://user-images.githubusercontent.com/5709615/57211138-c6963b00-7011-11e9-87c5-7c2642dcf5a0.png)

Or I have entered my postgreSQL credentials... still goes blank page 



In addition, how can we access the wordpress site via FTP on Heroku ?

**Comment by javadev** [comment]
I created new application successfully.

![postgres](https://user-images.githubusercontent.com/348496/57211324-88385600-6fe8-11e9-8650-4cd9cbd4fec9.png)

![choose-database](https://user-images.githubusercontent.com/348496/57211357-a8681500-6fe8-11e9-85b2-4d6eb0f1e980.png)
