### ISSUE TITLE
Can you add ClearDB for MySQL?

### ISSUE THREAD

**Issue by dangaplanh** [php4dev/heroku-wordpress#16]
Hi There,
Thanks for your awesome repo.

Could you please add the option for ClearDB?

Thanks

**Comment by javadev** [comment]
You may check this branch https://github.com/php4dev/heroku-wordpress/tree/mysql

**Comment by javadev** [comment]
We need to change env variable and delete  `wp-content/db.php`.

![image](https://user-images.githubusercontent.com/348496/100071737-0e72f200-2e44-11eb-8478-af13c61a5a60.png)
