### ISSUE TITLE
backblaze b2 as amazon s3 for storage

### ISSUE THREAD

**Issue by todokku** [php4dev/heroku-wordpress#2]
Hi php4dev ,
at the first thanks for your works ,
if its possible make changes to use backblaze b2 as amazon s3 because so cheapest:
https://www.backblaze.com/b2/cloud-storage-pricing.html
waiting for your response
finest regards

**Comment by javadev** [comment]
Hi todokku,

You may try this plugin.

https://github.com/cloudverve/wordpress-cloud-media-offloader-plugin

Have a nice day!
