### ISSUE TITLE
how can be install my own wordpress theme ?

### ISSUE THREAD

**Issue by todokku** [php4dev/heroku-wordpress#3]
Hi php4dev,
how can be install my own wordpress theme ?
waiting for your response
finest regards
goodbye

**Comment by LeGroupeNjt** [comment]
Hi PHP4dev .
I followed the instructions until the postgres step so i decided to install cleard db add on unstead of it.
i pushed my project to heroku master branch and i opend the app from cli.

but something went wrong i dont know what is it exactly :
cheeck my link  bellow :
https://blooming-woodland-75523.herokuapp.com/

**Comment by javadev** [comment]
Hi @todokku,

You need to clone a repository, commit your theme and deploy the application to heroku.
