### ISSUE TITLE
Database password

### ISSUE THREAD

**Issue by eduarperu** [php4dev/heroku-wordpress#33]
When opening the application, I got this message:

"Connecting to your PostgreSQL database without a password is considered insecure.
If you want to do it anyway, please set "PG4WP_INSECURE" to true in your "db.php" file."

How can I solve this issue?

**Comment by javadev** [comment]
You need a setting DATABASE_URL

![image](https://user-images.githubusercontent.com/348496/118094743-ccc90a00-b3d7-11eb-83be-b0156b7fec3e.png)

![image](https://user-images.githubusercontent.com/348496/118094839-f08c5000-b3d7-11eb-8213-2e2d4fdf1848.png)

**Comment by javadev** [comment]
@eduarperu What database do you use postgresql or mysql?
