### ISSUE TITLE
installation failed 

### ISSUE THREAD

**Issue by LeGroupeNjt** [php4dev/heroku-wordpress#4]
Hi PHP4dev .
I followed the instructions until the postgres step so i decided to install cleard db add on unstead of it.
i pushed my project to heroku master branch and i opend the app from cli.

but something went wrong i dont know what is it exactly :
cheeck my link bellow :
https://blooming-woodland-75523.herokuapp.com/

**Comment by javadev** [comment]
Hi @LeGroupeNjt,

Please add log messages.

**Comment by javadev** [comment]
This repository was tested only with postgres sql.
